### PR TITLE
Prevent SQL injection attack by escaping query values

### PR DESCRIPTION
**Pull request by rygine**
Noticed you were using query values without escaping them. This will allow anyone to do malicious things to your database. Merge this in ASAP!
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/andrewda/CSGOItemDB.com/pull/6%23issuecomment-149649216%22%2C%20%22https%3A//github.com/andrewda/CSGOItemDB.com/pull/6%23issuecomment-149652628%22%2C%20%22https%3A//github.com/andrewda/CSGOItemDB.com/pull/6%23issuecomment-149653979%22%2C%20%22https%3A//github.com/andrewda/CSGOItemDB.com/pull/6%23issuecomment-149654073%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/andrewda/CSGOItemDB.com/pull/6%23issuecomment-149649216%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Side%20note%3A%20Since%20I%20don%27t%20know%20the%20structure%20of%20your%20database%2C%20I%27m%20unable%20to%20test%20this.%20Be%20sure%20to%20run%20some%20tests%20before%20merging.%22%2C%20%22created_at%22%3A%20%222015-10-20T18%3A02%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2925672%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rygine%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27ll%20test%20this%20out%2C%20thanks%21%22%2C%20%22created_at%22%3A%20%222015-10-20T18%3A16%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10191084%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/andrewda%22%7D%7D%2C%20%7B%22body%22%3A%20%22Works%20like%20a%20charm%21%20Merging.%22%2C%20%22created_at%22%3A%20%222015-10-20T18%3A20%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10191084%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/andrewda%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-10-20T18%3A20%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10191084%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/andrewda%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/andrewda%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10191084%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/andrewda'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/andrewda/CSGOItemDB.com/pull/6#issuecomment-149649216'>General Comment</a></b>
- <a href='https://github.com/rygine'></a> Side note: Since I don't know the structure of your database, I'm unable to test this. Be sure to run some tests before merging.
- <a href='https://github.com/andrewda'></a> I'll test this out, thanks!
- <a href='https://github.com/andrewda'></a> Works like a charm! Merging.

<a href='https://www.codereviewhub.com/andrewda/CSGOItemDB.com/pull/6?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/andrewda/CSGOItemDB.com/pull/6?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/andrewda/CSGOItemDB.com/pull/6?approve=0'></a>&nbsp;<a href='https://github.com/andrewda/CSGOItemDB.com/pull/6'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andrewda** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/andrewda/CSGOItemDB.com/pull/6'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by rygine** [comment]
Side note: Since I don't know the structure of your database, I'm unable to test this. Be sure to run some tests before merging.

**Comment by andrewda** [comment]
I'll test this out, thanks!

**Comment by andrewda** [comment]
Works like a charm! Merging.

**Comment by andrewda** [comment]
:shipit:

**Pull request merged**
