### PR TITLE
Added API Register Page

### LINKED ISSUE #5: Add a way to create an API key

### PR DESCRIPTION
**Pull request by mvegter**
Should fix #5

### CODE REVIEW

**Comment by andrewda** [comment]
Holy cow, thanks for all this! I'll check it out in a while.

**Comment by mvegter** [comment]
@andrewda Yeah, had a free afternoon 😄

**Comment by andrewda** [comment]
Just tried running this and got this error:

```
TypeError: Cannot read property 'key' of null
    at ApiKeys.findOne (/home/ubuntu/workspace/CSGOItemDB/server.js:77:14)
    at model.Query.<anonymous> (/home/ubuntu/workspace/CSGOItemDB/node_modules/mongoose/lib/model.js:3433:16)
    at /home/ubuntu/workspace/CSGOItemDB/node_modules/kareem/index.js:273:21
    at /home/ubuntu/workspace/CSGOItemDB/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Looks like it's trying to get a user's key before they have finished registering if it's a new user.

**Comment by andrewda** [comment]
Not sure if it's the cleanest fix, but changing the `/` router to this seems to work:

```js
app.get('/', (req, res) => {
	if(req.user !== undefined) {
		ApiKeys.findOne({
			steamid: req.user.steamid
		}, (err, key) => {
			if(err) {
				throw err;
			} else if (key) {
				console.log(key)
				res.render('main', {
					user: req.user,
					key: key.key
				});
			} else {
				res.redirect('/api/register');
			}
		});
	} else {
		res.render('main', {
			user: req.user,
			key: key
		});		
	}
});
```

**Comment by andrewda** [comment]
Actually, a cleaner way might be just to redirect users that have just logged in through Steam to `/api/register`:

```js
app.get(/^\/auth\/steam(\/return)?$/,
	passport.authenticate('steam', { failureRedirect: '/' }),
	(req, res) => {
		res.redirect('/api/register');
	});
```

**Comment by mvegter** [comment]
@andrewda I believe it should be fixed now, add an ELSE statement in case it still doesn't fetch the key, to prevent an endless load time.

**Pull request closed without merging**
